[pytest]
addopts = -vs --reruns=1 --alluredir ./test_report/test_report_data/ --clean-alluredir
testpaths = ./test_case_po
python_files = test_*.py
python_classes = Test*
python_functions = test_*

;[pytest]
;addopts = -vs --reruns 0 --alluredir ./Report/HtmlData --clean-alluredir -p no:warnings -m second
;testpaths = ./TestCase ./TestCase
;python_files = Test_*.py
;python_classes = Test_*
;python_functions = test_*
;
;markers =
;    first
;    second
